export const Constants = {
 
    // Fetch todoList
    FETCH_TODOS: 'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_ERROR: 'FETCH_TODOS_ERROR',

    // add Todo
    ADD_NEW_TODO: 'ADD_NEW_TODO',
    ADD_NEW_TODO_SUCCESS: 'ADD_NEW_TODO_SUCCESS',
    ADD_NEW_TODO_ERROR: 'ADD_NEW_TODO_ERROR',

    // edit Todo
    EDIT_TODO_POST: 'EDIT_TODO_POST',
    EDIT_TODO_POST_SUCCESS: 'EDIT_TODO_POST_SUCCESS',
    EDIT_TODO_POST_ERROR: 'EDIT_TODO_POST_ERROR',

    // delete Todo
    DELETE_TODO: 'DELETE_TODO',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',
}