export const Constants = {
 
    // Fetch todoList
    FETCH_TODOS: 'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_ERROR: 'FETCH_TODOS_ERROR',

    // add Todo
    ADD_NEW_TODO: 'ADD_NEW_TODO',
    ADD_NEW_TODO_SUCCESS: 'ADD_NEW_TODO_SUCCESS',
    ADD_NEW_TODO_ERROR: 'ADD_NEW_TODO_ERROR',

    // edit Todo
    EDIT_TODO: 'EDIT_TODO',
    EDIT_TODO_SUCCESS: 'EDIT_TODO_SUCCESS',
    EDIT_TODO_ERROR: 'EDIT_TODO_ERROR',

    // activeTodoItem
    SET_ACTIVE_TODO: 'SET_ACTIVE_TODO',

    // delete Todo
    DELETE_TODO: 'DELETE_TODO',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_ERROR: 'DELETE_TODO_ERROR',
}